"""add participation applications

Revision ID: 36ea39123b3c
Revises: 376f2aff6541
Create Date: 2026-07-29 10:25:45.578684

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "36ea39123b3c"
down_revision = "376f2aff6541"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participation_applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("max_user_id", sa.BigInteger(), nullable=False),
        sa.Column("activity", sa.String(length=32), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("equipment", sa.String(length=32), nullable=True),
        sa.Column("equipment_other", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("performance_description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="new", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["max_user_id"], ["users.max_user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "max_user_id", "activity", name="uq_participation_application_user_activity"
        ),
    )
    with op.batch_alter_table("participation_applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_participation_applications_max_user_id"),
            ["max_user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participation_applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_participation_applications_max_user_id"))

    op.drop_table("participation_applications")
    # ### end Alembic commands ###
